name: Compile SCSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Sass
        run: npm install -g sass

      - name: Create CSS directory if not exists
        run: test -d css || mkdir css

      - name: Compile SCSS
        run: sass scss/styles.scss css/styles.css
