name: Compile SCSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS
        run: sass scss/styles.scss css/styles.css
